# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel
sudo: false
cache: packages

r_binary_packages:
  - biobase
  - biocgenerics
  - genomicranges
  - iranges
  - limma
  - ggplot2
  - plyr
  - stringr
  - testthat,
  - reshape2
  - rsqlite
  - rcppeigen
